version: "3.8"

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.0
    restart: always
    environment:
      KC_DB_URL: "jdbc:postgresql://postgres:5432/keycloak"
      KC_METRICS_ENABLED: "true"
      KC_DB_USERNAME: pgadmin
      KC_DB_PASSWORD: pgpassword
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: INFO
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - ./keycloak/config:/opt/keycloak/data/import
      - ./keycloak/providers:/opt/keycloak/providers
    command: "start --import-realm --db=postgres --http-enabled=true --http-port=8080 --hostname-strict=false --hostname-strict-https=false --spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true "
    healthcheck:
      # wait for the JWK url to be available
      test: curl --fail http://127.0.0.1:8080/realms/app-realm/.well-known/openid-configuration || exit 1
      interval: 10s
      retries: 50
      start_period: 0s
      timeout: 3s
  proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
    restart: always
    # see https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview
    environment:
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_CLIENT_ID: oauth2-proxy
      OAUTH2_PROXY_CLIENT_SECRET: "9htf4MohQEbbo64lcijfVvzw9Klgjfg5"
      OAUTH2_PROXY_REDIRECT_URL: "http://127.0.0.1:3000/oauth2/callback"
      OAUTH2_PROXY_OIDC_ISSUER_URL: "http://keycloak:8080/realms/app-realm"
#      OAUTH2_PROXY_SKIP_OIDC_DISCOVERY: true # because 127.0.0.1:8080 is not valid inside docker-compose network
#      OAUTH2_PROXY_OIDC_JWKS_URL: "http://127.0.0.1:8080/realms/app-realm/.well-known/openid-configuration"
      OAUTH2_PROXY_COOKIE_SECRET: 580b11331e148cacf8428190758c4fe2
      OAUTH2_PROXY_COOKIE_SECURE: false # for local env only
      OAUTH2_PROXY_SHOW_DEBUG_ON_ERROR: true # for local env only
      OAUTH2_PROXY_EMAIL_DOMAINS: "*" # allow any email
      OAUTH2_PROXY_UPSTREAMS: "http://front:8080/"
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_BANNER: "Login to keycloak to access the app"
      OAUTH2_PROXY_FOOTER: "SocialGouv"
      OAUTH2_PROXY_CUSTOM_SIGN_IN_LOGO: "https://socialgouv.github.io/support/img/marianne.jpeg"
      #OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: true
      # OAUTH2_PROXY_ALLOWED_ROLE: <realm role name> // Optional, required realm role
      # OAUTH2_PROXY_ALLOWED_ROLE: <client id>:<client role name> // Optional, required client role
    ports:
      - 3000:4180
    depends_on:
      keycloak:
        condition: service_healthy

  # this service is not exposed directly bu behind oauth2-proxy
  front:
    image: pengbai/docker-supermario
    restart: always
    # ports:
    #   - 8084:8080
